# Generated by Django 3.1.3 on 2020-11-27 12:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0004_remove_product_supplier'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='ProductQuantity',
            new_name='Quantity',
        ),
    ]
