# Generated by Django 3.1.3 on 2020-11-27 23:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0005_auto_20201127_1822'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Quantity',
            new_name='Supplied',
        ),
    ]
