# Generated by Django 3.1.3 on 2020-12-27 14:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0008_customer_sale'),
    ]

    operations = [
        migrations.AlterField(
            model_name='supplied',
            name='product',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='supplied', to='dashboard.product'),
        ),
        migrations.AlterField(
            model_name='supplied',
            name='supplier',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='supplied', to='dashboard.supplier'),
        ),
    ]
